--Procedmiento almacenado para Reporte
CREATE PROC sp_Reportes
@TipoReporte VARCHAR(20)
AS
BEGIN
	IF @TipoReporte = 'CLIENTE'
		SELECT * FROM CLIENTE
	IF @TipoReporte = 'PRODUCTO'
		SELECT * FROM PRODUCTO
	IF @TipoReporte = 'VENTAS'
	BEGIN
		SELECT C.CI, C.NOMBRE, P.CODIGO, P.DESCRIPCION, V.FECHA_VENTA,
		V.CANTIDAD_VENDIDA, V.PRECIO_UNITARIO, V.PRECIO_TOTAL
		FROM CLIENTE C, PRODUCTO P, VENTAS V
		WHERE C.CI = V.CI AND P.CODIGO = V.CODIGO
	END
END


--Procedmiento almacenado para DATOS DEL CLIENTE
CREATE PROC sp_Cliente
@CI VARCHAR (11),
@NOMBRE VARCHAR (50),
@CELULAR INT,
@ESTADO_CIVIL VARCHAR(10),
@NACIMIENTO VARCHAR(10),
@ACCION VARCHAR(10)
AS
BEGIN
	IF @ACCION = 'INSERTAR'
		INSERT INTO CLIENTE VALUES(@CI, @NOMBRE, @CELULAR, @ESTADO_CIVIL, @NACIMIENTO)
	IF @ACCION = 'ACTUALIZAR'
	BEGIN
		UPDATE CLIENTE SET NOMBRE=@NOMBRE,
		CELULAR=@CELULAR, ESTADO_CIVIL=@ESTADO_CIVIL,
		NACIMIENTO=@NACIMIENTO
		WHERE CI=@CI
	END
	IF @ACCION = 'ELIMINAR'
		DELETE CLIENTE WHERE CI=@CI
END


--Procedmiento almacenado para DATOS DEL PRODUCTO
CREATE PROC sp_Producto
@CODIGO VARCHAR (10),
@DESCRIPCION VARCHAR (50),
@MARCA VARCHAR (20),
@CANTIDAD INT,
@PRECIO_UNITARIO MONEY,
@ACCION VARCHAR(10)
AS
BEGIN
	IF @ACCION = 'INSERTAR'
		INSERT INTO PRODUCTO VALUES(@CODIGO, @DESCRIPCION, @MARCA, @CANTIDAD, @PRECIO_UNITARIO)
	IF @ACCION = 'ACTUALIZAR'
	BEGIN
		UPDATE PRODUCTO SET DESCRIPCION= @DESCRIPCION,
		MARCA=@MARCA, CANTIDAD=@CANTIDAD,
		PRECIO_UNITARIO=@PRECIO_UNITARIO
		WHERE CODIGO=@CODIGO
	END
	IF @ACCION = 'ELIMINAR'
		DELETE PRODUCTO WHERE CODIGO=@CODIGO
END
