--Procedmiento almacenado para Reporte
CREATE PROC sp_Reportes
@TipoReporte VARCHAR(20)
AS
BEGIN
	IF @TipoReporte = 'CLIENTE'
		SELECT * FROM CLIENTE
	IF @TipoReporte = 'PRODUCTO'
		SELECT * FROM PRODUCTO
	IF @TipoReporte = 'VENTAS'
	BEGIN
		SELECT C.CI, C.NOMBRE, P.CODIGO, P.DESCRIPCION, V.FECHA_VENTA,
		V.CANTIDAD_VENDIDA, V.PRECIO_UNITARIO, V.PRECIO_TOTAL
		FROM CLIENTE C, PRODUCTO P, VENTAS V
		WHERE C.CI = V.CI AND P.CODIGO = V.CODIGO
	END
END
